---
- name: Install Docker
  ansible.builtin.import_tasks: install_docker.yml

- name: Initialize Swarm manager
  ansible.builtin.import_tasks: init_swarm.yml
  when: inventory_hostname == groups['swarm_nodes'][0]

- name: Join Swarm workers
  ansible.builtin.import_tasks: join.yml
  when: inventory_hostname != groups['swarm_nodes'][0]

- name: Create overlay networks
  ansible.builtin.import_tasks: network.yml
  when: inventory_hostname == groups['swarm_nodes'][0]