---
- name: Reconfigure GitLab
  ansible.builtin.command:
    cmd: /usr/bin/gitlab-ctl reconfigure
  changed_when: true

- name: Save iptables
  ansible.builtin.shell: |
    mkdir -p /etc/iptables
    iptables-save > /etc/iptables/rules.v4
  changed_when: false