---
- name: Create APT keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Copy consul binary
  copy:
    src: "/home/vladimir/Downloads/consul"
    dest: "/usr/bin"
    mode: "0755"

- name: Create consul system group
  group:
    name: consul
    system: yes

- name: Create consul system user  
  user:
    name: consul
    group: consul
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
    home: /var/lib/consul

- name: Create Consul data directory
  file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
    mode: '0750'

- name: Consul systemd configuration
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service

- name: Create Consul configuration directory
  file:
    path: /etc/consul.d
    state: directory
    owner: consul
    group: consul
    mode: '0755'

- name: Deploy Consul configuration
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: '0640'
  notify: restart consul

- name: Ensure Consul is enabled and running
  systemd:
    name: consul
    state: started
    enabled: yes