---
- name: Install WireGuard prerequisites
  ansible.builtin.import_tasks: setup.yml
  tags: [always]

- name: Generate WireGuard keys
  ansible.builtin.import_tasks: generate_keys.yml
  tags: [keys]

- name: Configure WireGuard
  ansible.builtin.import_tasks: configure.yml
  tags: [config]