---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: restart haproxy

- name: Ensure HAProxy is enables and running
  running:
    systemd:
      name: haproxy
      state: started
      enabled: yes