---
k8s_kernel_modules:
  - overlay
  - br_netfilter

k8s_sysctl_params:
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.ipv4.ip_forward: "1"

k8s_base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - socat
  - conntrack

k8s_python_packages:
  - python3-kubernetes
  - python3-yaml

k8s_mount_bpf: true