---
- name: Deploy monitoring server
  hosts: monitoring
  become: true
  roles:
    - monitoring_server

# - name: Deploy monitoring agents
#   hosts: all:!monitoring
#   become: true
#   roles:
#     - monitoring_agents