---
- name: Deploy GitLab Master
  hosts: gitlab_master
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure base OS configuration
      ansible.builtin.import_role:
        name: common

  roles:
    - role: gitlab/master
      tags: [gitlab, master]

- name: Deploy GitLab Runner
  hosts: gitlab_runner
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure base OS configuration
      ansible.builtin.import_role:
        name: common

  roles:
    - role: gitlab/runner
      tags: [gitlab, runner]