---
- name: Setup bastion NAT
  hosts: bastion
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure base OS configuration
      ansible.builtin.import_role:
        name: common

  roles:
    - role: vpn/bastion_nat
      tags: [vpn, nat]

- name: Setup routes for all VPC nodes
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure base OS configuration
      ansible.builtin.import_role:
        name: common

  roles:
    - role: vpn/routes
      tags: [vpn, routes]
      when: vpc_node | default(false) | bool

- name: Setup WireGuard
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure base OS configuration
      ansible.builtin.import_role:
        name: common

  roles:
    - role: vpn/wireguard
      tags: [vpn, wireguard]
      when: inventory_hostname in wg_peers