---
- name: Setup bastion NAT
  hosts: bastion
  become: true
  roles:
    - role: vpn/bastion_nat
      tags: [vpn, nat]

- name: Generate WireGuard keys
  hosts: bastion,monitoring
  become: true
  roles:
    - role: vpn/wireguard
      tasks_from: generate_keys
      tags: [vpn, wireguard, keys]

- name: Configure WireGuard
  hosts: bastion,monitoring
  become: true
  roles:
    - role: vpn/wireguard
      tasks_from: configure
      tags: [vpn, wireguard, config]