---
- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: present

- name: NAT for swarm nodes
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: 192.168.10.0/24
    jump: MASQUERADE
    comment: "NAT Docker Swarm VPC"
  notify: Save iptables

- name: Allow forward from swarm
  ansible.builtin.iptables:
    chain: FORWARD
    source: 192.168.10.0/24
    jump: ACCEPT

- name: Allow established back
  ansible.builtin.iptables:
    chain: FORWARD
    destination: 192.168.10.0/24
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT