name: Terraform Destroy

on:
  workflow_dispatch: # Позволяет запустить удаление вручную кнопкой в интерфейсе

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "auto"
      TF_VAR_timeweb_token: ${{ secrets.TIMEWEB_TOKEN }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      R2_ENDPOINT: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.R2_BUCKET || 'terraform-state' }}" \
            -backend-config="key=kubernetes-cluster/terraform.tfstate" \
            -backend-config="endpoint=${{ env.R2_ENDPOINT }}" \
            -backend-config="access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
            -backend-config="skip_credentials_validation=true" \
            -backend-config="skip_region_validation=true" \
            -backend-config="skip_metadata_api_check=true" \
            -backend-config="use_path_style=true" \
            -backend-config="skip_requesting_account_id=true" \
            -reconfigure

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
